"""Synthetic random-vs-random battle generator with production-quality teams.

Pipeline:
    1. Load pre-generated PS teams from data/team_pools/gen{N}randombattle.jsonl
       (generated by ps-server-gen9/gen_teams.js — genuine PS random battle teams
       with correct levels, role-based movesets, guaranteed type coverage).
    2. Run battles with poke-engine, sampling stochastic branches.
    3. Encode states from each player's partial-observability perspective:
       - Opponent species revealed only as they switch in / use moves.
       - Moves revealed only when used; item/ability only when triggered.
       - HP, stat boosts, status, volatile effects synced from engine every turn.
    4. Label outcomes with Foul Play eval on timeout; ±1 on game-end.
"""
from __future__ import annotations

import argparse
import json
import math
import multiprocessing as mp
import pickle
import random
import sys
from dataclasses import dataclass, field as dc_field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
for _p in [str(ROOT), str(SRC)]:
    if _p not in sys.path:
        sys.path.insert(0, _p)

from typing import Any

from pipeline.sample_types import TrainingSample
from model.engine_bridge import battle_to_poke_engine_state
from model.state import Vocabulary, build_vocabulary, encode_state, normalize_name


# ------------------------------------------------------------------ #
# Worker-global state (populated by multiprocessing initialiser)      #
# ------------------------------------------------------------------ #

POOL: dict[str, Any] = {}
VOCAB: Vocabulary | None = None
LEARNSETS: dict[str, Any] = {}
POOLS_DIR: str = "data/team_pools"
_TEAM_POOLS: dict[str, list[str]] = {}  # gen_key -> list of packed team strings


def _load_poke_engine() -> Any:
    try:
        import poke_engine  # type: ignore[import-not-found]
    except Exception as exc:
        raise RuntimeError("poke_engine is required for synthetic generation") from exc
    return poke_engine


def init_worker(
    pool: dict[str, Any],
    vocab: Vocabulary,
    learnsets: dict[str, Any],
    pools_dir: str = "data/team_pools",
) -> None:
    global POOL, VOCAB, LEARNSETS, POOLS_DIR
    POOL = pool
    VOCAB = vocab
    LEARNSETS = learnsets
    POOLS_DIR = pools_dir


# ------------------------------------------------------------------ #
# Partial-observability tracking                                       #
# ------------------------------------------------------------------ #

@dataclass
class BattleObservationState:
    """Tracks what one player has directly observed about the opponent."""
    revealed_slots: set[int]
    revealed_moves: dict[int, set[str]]
    revealed_items: dict[int, str | None]
    revealed_abilities: dict[int, str | None]
    last_move: dict[int, str | None]    # slot → last move used (Choice lock signal)
    fainted_slots: set[int]             # slots confirmed fainted (distinct from unrevealed)

    @classmethod
    def initial(cls, active_slot: int) -> "BattleObservationState":
        """Battle starts — active slot species revealed, nothing else known."""
        return cls(
            revealed_slots={active_slot},
            revealed_moves={active_slot: set()},
            revealed_items={},
            revealed_abilities={},
            last_move={},
            fainted_slots=set(),
        )

    def update_after_move(
        self,
        opp_active_slot: int,
        move_used: str | None,
        item_activated: str | None = None,
        ability_triggered: str | None = None,
    ) -> None:
        self.revealed_slots.add(opp_active_slot)
        self.revealed_moves.setdefault(opp_active_slot, set())
        if move_used:
            self.revealed_moves[opp_active_slot].add(move_used)
            self.last_move[opp_active_slot] = move_used
        if item_activated:
            self.revealed_items[opp_active_slot] = item_activated
        if ability_triggered:
            self.revealed_abilities[opp_active_slot] = ability_triggered

    def update_after_switch(self, new_active_slot: int) -> None:
        """Opponent switches in — new slot species now revealed."""
        self.revealed_slots.add(new_active_slot)
        self.revealed_moves.setdefault(new_active_slot, set())

    def update_after_faint(self, slot: int) -> None:
        """Opponent mon fainted — mark as revealed-and-fainted regardless of prior state."""
        self.revealed_slots.add(slot)
        self.fainted_slots.add(slot)


def mask_opponent_for_p1(
    full_opp_team: list[dict[str, Any]],
    obs: BattleObservationState,
    active_opp_slot: int,
) -> list[dict[str, Any] | None]:
    """
    Return the opponent team from the observing player's partial-information view.

    Unrevealed slots → None  (encode_state maps None to full-UNKNOWN token).
    Revealed slots   → subset of known info: species always visible once seen,
                       moves only those actually used, item/ability only if triggered.
    Fainted slots encode with hp_fraction=0.0 (distinct from UNKNOWN).
    last_move included so the value head can detect Choice-locked opponents.
    """
    visible: list[dict[str, Any] | None] = []
    for idx, mon in enumerate(full_opp_team):
        if idx not in obs.revealed_slots:
            visible.append(None)
        else:
            is_fainted = idx in obs.fainted_slots
            is_active = idx == active_opp_slot
            visible.append({
                "species": mon["species"],
                "moves": sorted(obs.revealed_moves.get(idx, set()))[:4],
                "item": obs.revealed_items.get(idx),
                "ability": obs.revealed_abilities.get(idx),
                "hp_fraction": 0.0 if is_fainted else mon.get("hp_fraction", 1.0),
                "is_active": is_active,
                "status": mon.get("status", "none"),
                "types": mon.get("types", []),
                "last_move": obs.last_move.get(idx),
                # Only expose live battle state for the active mon
                "boosts": mon.get("boosts", {}) if is_active else {},
                "volatile_effects": mon.get("volatile_effects", []) if is_active else [],
                "must_recharge": mon.get("must_recharge", False) if is_active else False,
            })
    return visible


# ------------------------------------------------------------------ #
# PS team pool (primary sampling path)                                 #
# ------------------------------------------------------------------ #

def _load_team_pool(gen: int, pools_dir: str) -> list[str]:
    """Load packed team strings for the given gen from the pre-generated pool."""
    key = f"gen{gen}"
    if key not in _TEAM_POOLS:
        path = Path(pools_dir) / f"gen{gen}randombattle.jsonl"
        if path.exists():
            _TEAM_POOLS[key] = [l.strip() for l in path.read_text().splitlines() if l.strip()]
        else:
            _TEAM_POOLS[key] = []
    return _TEAM_POOLS[key]


def unpack_ps_team(packed: str, gen: int) -> list[dict[str, Any]]:
    """
    Parse a PS packed team string into our team dict format.

    Packed format per Pokemon (separated by ']'):
        name|species|item|ability|moves|nature|evs|gender|ivs|shiny|level|...
    If 'species' is blank, 'name' is the species.
    """
    result: list[dict[str, Any]] = []
    for slot in packed.strip().split("]"):
        slot = slot.strip()
        if not slot:
            continue
        parts = slot.split("|")
        if len(parts) < 4:
            continue
        nickname = parts[0].strip()
        species_raw = parts[1].strip() if parts[1].strip() else nickname
        item = normalize_name(parts[2].strip()) if len(parts) > 2 else ""
        ability = normalize_name(parts[3].strip()) if len(parts) > 3 else ""
        moves_str = parts[4].strip() if len(parts) > 4 else ""
        moves = [normalize_name(m.strip()) for m in moves_str.split(",") if m.strip()][:4]
        level = 100
        if len(parts) > 10 and parts[10].strip().isdigit():
            level = int(parts[10].strip())
        result.append({
            "species": normalize_name(species_raw),
            "moves": moves,
            "item": item,
            "ability": ability,
            "level": level,
            "hp_fraction": 1.0,
            "is_active": False,
            "status": "none",
            "boosts": {},
            "volatile_effects": [],
            "toxic_count": 0,
            "sleep_turns": 0,
            "last_move": None,
            "must_recharge": False,
            "pp": [35, 35, 35, 35],
        })
    return result


def sample_team_from_pool(
    gen: int,
    rng: random.Random,
    pools_dir: str = "data/team_pools",
) -> list[dict[str, Any]] | None:
    """Sample a genuine PS random battle team from the pre-generated pool.

    Returns None if the pool is unavailable (fall back to sample_team_legacy).
    """
    pool = _load_team_pool(gen, pools_dir)
    if not pool:
        return None
    packed = rng.choice(pool)
    team = unpack_ps_team(packed, gen)
    if len(team) < 2:
        return None
    return team


# ------------------------------------------------------------------ #
# Legacy team sampler (fallback when pools unavailable)                #
# ------------------------------------------------------------------ #

def stat_calc(base: int, level: int, hp: bool = False, ev: int = 85, iv: int = 31) -> int:
    common = math.floor(((2 * int(base) + iv + math.floor(ev / 4)) * level) / 100)
    return common + level + 10 if hp else common + 5


def stats_from_pokedex(
    pokedex_entry: dict[str, Any],
    level: int,
    set_stats: dict[str, Any] | None = None,
) -> dict[str, int]:
    if set_stats:
        return {
            "hp":  int(set_stats.get("hp",  set_stats.get("maxhp", 100))),
            "atk": int(set_stats.get("atk", set_stats.get("attack", 100))),
            "def": int(set_stats.get("def", set_stats.get("defense", 100))),
            "spa": int(set_stats.get("spa", set_stats.get("special_attack", 100))),
            "spd": int(set_stats.get("spd", set_stats.get("special_defense", 100))),
            "spe": int(set_stats.get("spe", set_stats.get("speed", 100))),
        }
    base = pokedex_entry.get("baseStats", {}) if isinstance(pokedex_entry, dict) else {}
    return {
        "hp":  stat_calc(base.get("hp",  100), level, hp=True),
        "atk": stat_calc(base.get("atk", 100), level),
        "def": stat_calc(base.get("def", 100), level),
        "spa": stat_calc(base.get("spa", 100), level),
        "spd": stat_calc(base.get("spd", 100), level),
        "spe": stat_calc(base.get("spe", 100), level),
    }


def legal_moves_for_species(
    species_id: str,
    gen: int,
    base_moves: list[str],
    rng: random.Random,
) -> list[str]:
    gen_key = f"gen{gen}"
    learnset_moves = list((LEARNSETS.get(species_id, {}) or {}).get(gen_key, []))
    if learnset_moves and rng.random() < 0.35:
        candidates = sorted(set(map(normalize_name, base_moves)) | set(learnset_moves))
    else:
        candidates = [normalize_name(move) for move in base_moves]
    candidates = [move for move in candidates if move and move != "none"]
    return candidates or ["tackle"]


def sample_team_legacy(pool: dict[str, Any], gen: int, rng: random.Random) -> list[dict[str, Any]]:
    """Legacy uniform sampler — used when PS team pools are unavailable."""
    gen_key = f"gen{gen}"
    eligible = [s for s, e in pool["species"].items() if gen_key in (e.get("sets") or {})]
    if not eligible:
        eligible = list(pool["species"].keys())
    selected = rng.sample(eligible, min(6, len(eligible)))
    team: list[dict[str, Any]] = []
    for species_id in selected:
        entry = pool["species"][species_id]
        gen_sets = (entry.get("sets") or {}).get(gen_key, [])
        if gen_sets:
            base_set = rng.choice(gen_sets)
        else:
            all_sets = [s for sets in (entry.get("sets") or {}).values() for s in sets]
            base_set = rng.choice(all_sets) if all_sets else {}
        all_moves = legal_moves_for_species(species_id, gen, list(base_set.get("moves") or []), rng)
        n_moves = rng.choices([1, 2, 3, 4], weights=[0.05, 0.10, 0.20, 0.65])[0]
        moves = rng.sample(all_moves, min(n_moves, len(all_moves)))
        level = int(base_set.get("level") or (100 if gen >= 6 else 50))
        pokedex_entry = entry.get("pokedex") or {}
        stats = stats_from_pokedex(pokedex_entry, level, base_set.get("stats") or None)
        team.append({
            "species": species_id,
            "moves": moves,
            "item": base_set.get("item", "") if gen >= 2 else "",
            "ability": base_set.get("ability", "") if gen >= 3 else "",
            "level": level,
            "types": pokedex_entry.get("types", ["normal"]),
            "hp_fraction": 1.0,
            "is_active": False,
            "status": "none",
            "boosts": {},
            "volatile_effects": [],
            "toxic_count": 0,
            "sleep_turns": 0,
            "last_move": None,
            "must_recharge": False,
            "pp": [35, 35, 35, 35],
        })
    if team:
        team[0]["is_active"] = True
    return team


def _sample_team(
    gen: int,
    rng: random.Random,
    pools_dir: str,
) -> list[dict[str, Any]]:
    """Sample a team: prefer PS pool, fall back to legacy sampler."""
    team = sample_team_from_pool(gen, rng, pools_dir)
    if team is not None:
        return team
    return sample_team_legacy(POOL, gen, rng)


# ------------------------------------------------------------------ #
# Engine helpers                                                       #
# ------------------------------------------------------------------ #

def teams_to_poke_engine_state(
    team1: list[dict[str, Any]],
    team2: list[dict[str, Any]],
    gen: int,
) -> Any:
    return battle_to_poke_engine_state({"own_team": team1, "opponent_team": team2, "generation": gen})


def has_healthy_pokemon(side: Any) -> bool:
    return any(getattr(mon, "hp", 0) > 0 for mon in list(getattr(side, "pokemon", []) or []))


def is_terminal(state: Any) -> bool:
    return not has_healthy_pokemon(state.side_one) or not has_healthy_pokemon(state.side_two)


def get_available_engine_moves(side: Any) -> list[str]:
    active = side.pokemon[int(side.active_index)]
    choices: list[str] = []
    for move in active.moves:
        if not move.disabled and move.id != "none" and move.pp > 0:
            choices.append(str(move.id))
    active_idx = int(side.active_index)
    for idx, mon in enumerate(side.pokemon):
        if idx != active_idx and mon.hp > 0:
            choices.append(f"switch {mon.id}")
    return choices or ["tackle"]


def move_only_choices(side: Any) -> list[str]:
    active = side.pokemon[int(side.active_index)]
    choices = [str(m.id) for m in active.moves if not m.disabled and m.id != "none" and m.pp > 0]
    return choices or ["tackle"]


def engine_move_to_action_index(side: Any, choice: str) -> int:
    active = side.pokemon[int(side.active_index)]
    if choice.startswith("switch "):
        target = choice.split(" ", 1)[1]
        active_idx = int(side.active_index)
        switches = [mon.id for idx, mon in enumerate(side.pokemon) if idx != active_idx and mon.hp > 0]
        return 4 + switches.index(target) if target in switches[:5] else 4
    for idx, move in enumerate(active.moves[:4]):
        if str(move.id) == choice:
            return idx
    return 0


def _alive_slots(side: Any) -> set[int]:
    """Return indices of mons with hp > 0 in the engine state."""
    return {
        i for i, mon in enumerate(list(getattr(side, "pokemon", []) or []))
        if float(getattr(mon, "hp", 0)) > 0
    }


def _moves_from_choice(choice: str) -> tuple[str | None, bool]:
    """Returns (move_name, is_switch)."""
    if choice.startswith("switch "):
        return None, True
    return choice, False


# Status string normalisation from poke-engine to our canonical set
_ENGINE_STATUS_MAP: dict[str, str] = {
    "none": "none", "burn": "brn", "brn": "brn",
    "freeze": "frz", "frz": "frz",
    "paralysis": "par", "par": "par",
    "poison": "psn", "psn": "psn",
    "toxic": "tox", "tox": "tox",
    "sleep": "slp", "slp": "slp",
}


def _sync_pokemon_state_from_engine(team: list[dict[str, Any]], side: Any) -> None:
    """
    Sync all mutable per-Pokémon state from poke-engine after every turn.

    Covers: HP fraction, stat boosts (all 5), status condition, volatile effects,
    toxic counter, sleep turns, PP, and must_recharge flag.

    This is the only place that writes back engine state into the team dicts.
    Calling it every turn ensures encoded states reflect actual in-battle dynamics
    rather than the static initial values from team sampling.
    """
    eng_mons = list(getattr(side, "pokemon", []) or [])[:len(team)]
    for idx, eng_mon in enumerate(eng_mons):
        # --- HP ---
        hp = float(getattr(eng_mon, "hp", 0))
        maxhp = float(getattr(eng_mon, "maxhp", 1) or 1)
        team[idx]["hp_fraction"] = hp / max(1.0, maxhp)

        # --- Stat boosts ---
        team[idx]["boosts"] = {
            "atk": int(getattr(eng_mon, "attack_boost",           0) or 0),
            "def": int(getattr(eng_mon, "defense_boost",          0) or 0),
            "spa": int(getattr(eng_mon, "special_attack_boost",   0) or 0),
            "spd": int(getattr(eng_mon, "special_defense_boost",  0) or 0),
            "spe": int(getattr(eng_mon, "speed_boost",            0) or 0),
        }

        # --- Status condition ---
        raw_status = str(getattr(eng_mon, "status", "None") or "None").lower()
        raw_status = raw_status.replace("status.", "").replace("_", "")
        team[idx]["status"] = _ENGINE_STATUS_MAP.get(raw_status, "none")

        # --- Toxic counter & sleep turns ---
        team[idx]["toxic_count"] = int(getattr(eng_mon, "toxic_count", 0) or 0)
        team[idx]["sleep_turns"] = int(getattr(eng_mon, "sleep_turns", 0) or 0)

        # --- Volatile statuses ---
        volatiles_raw = getattr(eng_mon, "volatile_statuses", set()) or set()
        volatiles_list = [str(v).lower() for v in volatiles_raw]
        team[idx]["volatile_effects"] = volatiles_list
        team[idx]["must_recharge"] = "mustrecharge" in volatiles_list

        # --- PP ---
        eng_moves = list(getattr(eng_mon, "moves", []) or [])
        team[idx]["pp"] = [
            int(getattr(m, "pp", 35) or 35) for m in eng_moves[:4]
        ] + [35] * max(0, 4 - len(eng_moves))


def _foul_play_eval(team1: list[dict[str, Any]], team2: list[dict[str, Any]]) -> float:
    """
    Simplified Foul Play static evaluation for timeout outcome labelling.

    Uses POKEMON_ALIVE_STATIC=30 + POKEMON_HP=100 components from Foul Play
    evaluate.py (Scoring class). Unrevealed mons count as alive (conservative).
    """
    def score_side(team: list[dict[str, Any]]) -> float:
        s = 0.0
        for mon in team:
            hp = float(mon.get("hp_fraction", 0.0))
            if hp > 0.0:
                s += 30.0 + 100.0 * hp
        return s
    return score_side(team1) - score_side(team2)


def _encode_partial_state(
    own_team: list[dict[str, Any]],
    masked_opp: list[dict[str, Any] | None],
    available_choices: list[str],
    turn: int,
    gen: int,
    vocab: Vocabulary,
    *,
    unrevealed_p2: int = 5,
    fainted_p2: int = 0,
    unrevealed_p1: int = 0,
    fainted_p1: int = 0,
    sleep_clause_p1: bool = False,
    sleep_clause_p2: bool = False,
) -> Any:
    """Encode a state from one player's partial-information perspective."""
    move_choices   = [c for c in available_choices if not c.startswith("switch ")]
    switch_choices = [c for c in available_choices if c.startswith("switch ")]
    return encode_state(
        {
            "turn": turn,
            "generation": gen,
            "own_team": own_team,
            "opponent_team": masked_opp,
            "available_moves": [{"move": m, "disabled": False} for m in move_choices[:4]],
            "available_switches": [{"species": m.split(" ", 1)[1]} for m in switch_choices[:5]],
            "unrevealed_p1": unrevealed_p1,
            "unrevealed_p2": unrevealed_p2,
            "fainted_p1": fainted_p1,
            "fainted_p2": fainted_p2,
            "sleep_clause_p1": int(sleep_clause_p1),
            "sleep_clause_p2": int(sleep_clause_p2),
        },
        vocab=vocab,
        generation=gen,
    )


# ------------------------------------------------------------------ #
# Main battle runner                                                   #
# ------------------------------------------------------------------ #

MAX_TURNS = 100  # Raised from 50 — captures endgame hazard/status/PP dynamics


def run_random_battle(
    pool: dict[str, Any],
    vocab: Vocabulary,
    gen: int,
    rng: random.Random,
    pools_dir: str = "data/team_pools",
) -> list[TrainingSample]:
    poke_engine = _load_poke_engine()
    team1 = _sample_team(gen, rng, pools_dir)
    team2 = _sample_team(gen, rng, pools_dir)
    if team1:
        team1[0]["is_active"] = True
    if team2:
        team2[0]["is_active"] = True
    state = teams_to_poke_engine_state(team1, team2, gen)

    active_p1 = int(state.side_one.active_index)
    active_p2 = int(state.side_two.active_index)

    # P1 observes P2's active species; P2 observes P1's active species.
    obs_p1 = BattleObservationState.initial(active_p2)
    obs_p2 = BattleObservationState.initial(active_p1)

    samples_p1: list[tuple[Any, int, int]] = []
    samples_p2: list[tuple[Any, int, int]] = []

    for turn in range(MAX_TURNS):
        if is_terminal(state):
            break

        p1_moves = get_available_engine_moves(state.side_one)
        p2_moves = get_available_engine_moves(state.side_two)
        if not p1_moves or not p2_moves:
            break

        p1_choice = rng.choice(p1_moves)
        p2_choice = rng.choice(p2_moves)

        # Active slots BEFORE this turn (for correct observation updates)
        active_p1_slot = int(state.side_one.active_index)
        active_p2_slot = int(state.side_two.active_index)
        p1_move, p1_is_switch = _moves_from_choice(p1_choice)
        p2_move, p2_is_switch = _moves_from_choice(p2_choice)

        # Compute context counts for field encoding
        unrevealed_p2_for_p1 = max(0, 6 - len(obs_p1.revealed_slots))
        fainted_p2_for_p1    = len(obs_p1.fainted_slots)
        unrevealed_p1_for_p2 = max(0, 6 - len(obs_p2.revealed_slots))
        fainted_p1_for_p2    = len(obs_p2.fainted_slots)
        fainted_p1_own       = sum(1 for m in team1 if m.get("hp_fraction", 1.0) <= 0.0)
        fainted_p2_own       = sum(1 for m in team2 if m.get("hp_fraction", 1.0) <= 0.0)
        sleep_clause_p1      = any(m.get("status") == "slp" for m in team1)
        sleep_clause_p2      = any(m.get("status") == "slp" for m in team2)

        # Encode states from each player's partial-info perspective
        masked_opp_for_p1 = mask_opponent_for_p1(team2, obs_p1, active_p2_slot)
        masked_opp_for_p2 = mask_opponent_for_p1(team1, obs_p2, active_p1_slot)

        encoded_p1 = _encode_partial_state(
            team1, masked_opp_for_p1, p1_moves, turn, gen, vocab,
            unrevealed_p2=unrevealed_p2_for_p1,
            fainted_p2=fainted_p2_for_p1,
            unrevealed_p1=0,
            fainted_p1=fainted_p1_own,
            sleep_clause_p1=sleep_clause_p1,
            sleep_clause_p2=sleep_clause_p2,
        )
        encoded_p2 = _encode_partial_state(
            team2, masked_opp_for_p2, p2_moves, turn, gen, vocab,
            unrevealed_p2=unrevealed_p1_for_p2,
            fainted_p2=fainted_p1_for_p2,
            unrevealed_p1=0,
            fainted_p1=fainted_p2_own,
            sleep_clause_p1=sleep_clause_p2,
            sleep_clause_p2=sleep_clause_p1,
        )

        action_p1 = engine_move_to_action_index(state.side_one, p1_choice)
        action_p2 = engine_move_to_action_index(state.side_two, p2_choice)

        samples_p1.append((encoded_p1, action_p1, turn))
        samples_p2.append((encoded_p2, action_p2, turn))

        # Remember which mons were alive before applying this turn
        alive_p1_pre = _alive_slots(state.side_one)
        alive_p2_pre = _alive_slots(state.side_two)

        # Apply the selected branch
        try:
            branches = poke_engine.generate_instructions(state, p1_choice, p2_choice)
        except Exception:
            p1_choice = rng.choice(move_only_choices(state.side_one))
            p2_choice = rng.choice(move_only_choices(state.side_two))
            try:
                branches = poke_engine.generate_instructions(state, p1_choice, p2_choice)
                p1_move, p1_is_switch = _moves_from_choice(p1_choice)
                p2_move, p2_is_switch = _moves_from_choice(p2_choice)
            except Exception:
                break
        if not branches:
            break

        weights = [max(0.0, float(getattr(b, "percentage", 0.0))) for b in branches]
        branch = rng.choices(branches, weights=weights if sum(weights) > 0 else None, k=1)[0]
        state = state.apply_instructions(branch)

        # --- Sync full engine state into team dicts ---
        _sync_pokemon_state_from_engine(team1, state.side_one)
        _sync_pokemon_state_from_engine(team2, state.side_two)

        # --- Track last move used (enables Choice lock signal) ---
        if not p1_is_switch and p1_move:
            team1[active_p1_slot]["last_move"] = p1_move
        if not p2_is_switch and p2_move:
            team2[active_p2_slot]["last_move"] = p2_move

        # --- Detect newly fainted mons and mark in observation ---
        for slot in alive_p1_pre - _alive_slots(state.side_one):
            obs_p2.update_after_faint(slot)
        for slot in alive_p2_pre - _alive_slots(state.side_two):
            obs_p1.update_after_faint(slot)

        # --- Update observation state (revealed moves / switches) ---
        if p2_is_switch:
            obs_p1.update_after_switch(int(state.side_two.active_index))
        else:
            obs_p1.update_after_move(active_p2_slot, p2_move)

        if p1_is_switch:
            obs_p2.update_after_switch(int(state.side_one.active_index))
        else:
            obs_p2.update_after_move(active_p1_slot, p1_move)

    # --- Outcome determination ---
    if not has_healthy_pokemon(state.side_two):
        outcome_p1 = 1.0
    elif not has_healthy_pokemon(state.side_one):
        outcome_p1 = -1.0
    else:
        # Timeout: use Foul Play static eval (HP + alive count)
        score = _foul_play_eval(team1, team2)
        outcome_p1 = 1.0 if score > 0 else (-1.0 if score < 0 else 0.0)

    battle_id = f"synthetic_gen{gen}_{rng.randint(0, 2**32)}"
    result: list[TrainingSample] = []
    for encoded, action, turn in samples_p1:
        result.append(TrainingSample(battle_id, turn, encoded, action, outcome_p1, {}, gen))
    for encoded, action, turn in samples_p2:
        result.append(TrainingSample(f"{battle_id}_p2", turn, encoded, action, -outcome_p1, {}, gen))
    return result


# ------------------------------------------------------------------ #
# Worker / batch infrastructure                                        #
# ------------------------------------------------------------------ #

def worker(task: tuple[int, int | None, int]) -> list[TrainingSample]:
    index, fixed_gen, seed = task
    rng = random.Random(seed + index * 9973)
    gen = int(fixed_gen or rng.randint(1, 9))
    assert VOCAB is not None
    return run_random_battle(POOL, VOCAB, gen, rng, pools_dir=POOLS_DIR)


def write_batch(output: Path, batch_index: int, samples: list[TrainingSample]) -> Path:
    output.mkdir(parents=True, exist_ok=True)
    path = output / f"synthetic_{batch_index:06d}.pkl"
    with path.open("wb") as handle:
        pickle.dump(samples, handle)
    return path


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate PS-accurate synthetic battles with partial observability"
    )
    parser.add_argument("--pool",       default="data/all_gen_pool.json")
    parser.add_argument("--learnsets",  default="data/learnsets.json")
    parser.add_argument("--output",     default="data/synthetic")
    parser.add_argument("--pools-dir",  default="data/team_pools")
    parser.add_argument("--n-battles",  type=int, default=10_000)
    parser.add_argument("--gen",        type=int, default=None)
    parser.add_argument("--workers",    type=int, default=8)
    parser.add_argument("--seed",       type=int, default=42)
    args = parser.parse_args()

    pool_data = json.loads(Path(args.pool).read_text(encoding="utf-8"))
    vocab     = build_vocabulary(args.pool)
    learnsets = (
        json.loads(Path(args.learnsets).read_text(encoding="utf-8"))
        if Path(args.learnsets).exists()
        else {}
    )
    output = Path(args.output)
    tasks  = [(index, args.gen, args.seed) for index in range(args.n_battles)]

    batch_samples: list[TrainingSample] = []
    batch_index = len(list(output.glob("synthetic_*.pkl"))) if output.exists() else 0
    completed = 0

    init_args = (pool_data, vocab, learnsets, args.pools_dir)
    if args.workers <= 1:
        init_worker(*init_args)
        iterator = map(worker, tasks)
    else:
        mp_pool = mp.Pool(args.workers, initializer=init_worker, initargs=init_args)
        iterator = mp_pool.imap_unordered(worker, tasks, chunksize=16)

    try:
        for samples in iterator:
            completed += 1
            batch_samples.extend(samples)
            if completed % 1000 == 0:
                path = write_batch(output, batch_index, batch_samples)
                print(json.dumps({
                    "battles": completed,
                    "samples": len(batch_samples),
                    "path": str(path),
                }))
                batch_index += 1
                batch_samples = []
        if batch_samples:
            path = write_batch(output, batch_index, batch_samples)
            print(json.dumps({
                "battles": completed,
                "samples": len(batch_samples),
                "path": str(path),
            }))
    finally:
        if args.workers > 1 and "mp_pool" in locals():
            mp_pool.close()
            mp_pool.join()


if __name__ == "__main__":
    main()
